name: matrifwofklow
on: workflow_dispatch
jobs:
 build:
   strategy:
    matrix:
     node-version: [12,13,14]
     operating-system: [ubuntu-latest,windows-latest]
     exclude:
        - node-version: 14
          operating-system: windows-latest 
    runs-on: ${{matrix.operating-system}}
   steps:
    - name: checkout the code
      uses: actions/checkout@v3
    - name: install nodejs
      uses: actions/setup-node@v3
      with: 
       node-version: ${{matrix.node-version}}
       

         
      
  
